# Generated by Django 4.0.1 on 2022-01-19 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter', '0002_dweet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dweet',
            old_name='created_ad',
            new_name='created_at',
        ),
    ]
