# Generated by Django 4.0.1 on 2022-01-20 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter', '0004_profile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
    ]
